openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/products/:
    get:
      operationId: listItems
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
          description: ''
      tags:
      - api
    post:
      operationId: createItem
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
      tags:
      - api
  /api/v1/products/{id}/:
    get:
      operationId: retrieveItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this item.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
      tags:
      - api
    put:
      operationId: updateItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this item.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this item.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Item'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Item'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Item'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyItem
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this item.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        description:
          type: string
        article:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
        price:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 100
          minimum: -100
        country:
          enum:
          - Fr
          - US
          - Ru
          - CH
          type: string
        color:
          type: string
          maxLength: 200
        date_created:
          type: string
          format: date-time
          readOnly: true
        image:
          type: string
          format: binary
          nullable: true
      required:
      - title
      - description
      - article
      - price
      - country
      - color
