# Generated by Django 4.0.3 on 2022-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('article', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('country', models.CharField(choices=[('Fr', 'France'), ('US', 'USA'), ('Ru', 'Russia'), ('CH', 'China')], max_length=150)),
                ('color', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ['date_created'],
            },
        ),
    ]
