# Generated by Django 4.0.3 on 2022-04-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bottype_item_bot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottype',
            options={'ordering': ['name'], 'verbose_name_plural': 'BotType'},
        ),
    ]
