# Generated by Django 4.0.3 on 2022-04-07 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_bottype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottype',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bottype',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
