# Generated by Django 4.0.3 on 2022-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_bottype_allowed_users_bottype_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottype',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bottype',
            name='telegram_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
