# Generated by Django 4.0.3 on 2022-04-10 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_bottype_link_bottype_telegram_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottype',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
