# Generated by Django 4.0.3 on 2022-04-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_bottype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='balance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='total_bought',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Всего куплено'),
        ),
        migrations.AddField(
            model_name='item',
            name='total_stock',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Всего на складе'),
        ),
    ]
